name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - name: run tests
      run:
        nix develop -c 'tox'
